### ISSUE TITLE
PRJD-39  Create and design the user account information edit page.

### ISSUE THREAD

**Issue by nrdmraju** [TheBradster/chec-nutrition-app#33]
Task: Create and implement the edit user profile information page.

Evaluation: Users will be able to access this page from the user profile page. There will be an edit information button on the user profile page that will direct the user to this edit page.

**Comment by nrdmraju** [comment]
The work for the issue has been completed. Issue33 is being closed.

**Comment by TheBradster** [comment]
Please don't close issues until the pull request has gone through.
