### ISSUE TITLE
PRJD-9: Being able to edit/cancel order

### ISSUE THREAD

**Issue by nrdmraju** [TheBradster/chec-nutrition-app#7]
**Task Description:** This task will build upon PRJD-10 as it will add features to the summary page for a specific order. The features will allow the user to edit their order more (more than 24 hours beforehand). If the user has a change in plans they can also cancel the order completely (also has to be done 24 hours in advance). 

**Evaluation:** After having successfully being able to view the summary of the order, the user will see two options at the bottom that will allow them to edit or cancel that order based off their current situation. After user has edited or cancelled their order this change should be reflected in the app database.

**Comment by jsdoublel** [comment]
The goal of this task is to create a way for a user to edit their orders. This will not require the creation of a new view as the one for placing order (with a few modifications) should be fine. However, some modification to the control code will be required. First, a way to call the place order page with an existing order, second a way to update the order in the week object, and third a way to cancel an order if the (to be created) cancel order button is pressed.
